# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc
import warnings

import specification_pb2 as specification__pb2

GRPC_GENERATED_VERSION = "1.70.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in specification_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class ServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateUser = channel.unary_stream(
            "/Server/CreateUser",
            request_serializer=specification__pb2.UserSignup.SerializeToString,
            response_deserializer=specification__pb2.UpdateHome.FromString,
            _registered_method=True,
        )
        self.Login = channel.unary_stream(
            "/Server/Login",
            request_serializer=specification__pb2.User.SerializeToString,
            response_deserializer=specification__pb2.UpdateHome.FromString,
            _registered_method=True,
        )
        self.Logout = channel.unary_stream(
            "/Server/Logout",
            request_serializer=specification__pb2.User.SerializeToString,
            response_deserializer=specification__pb2.Empty.FromString,
            _registered_method=True,
        )
        self.SearchUsers = channel.unary_stream(
            "/Server/SearchUsers",
            request_serializer=specification__pb2.SearchPattern.SerializeToString,
            response_deserializer=specification__pb2.UserList.FromString,
            _registered_method=True,
        )
        self.DeleteAccount = channel.unary_stream(
            "/Server/DeleteAccount",
            request_serializer=specification__pb2.User.SerializeToString,
            response_deserializer=specification__pb2.Empty.FromString,
            _registered_method=True,
        )
        self.SendMessage = channel.unary_stream(
            "/Server/SendMessage",
            request_serializer=specification__pb2.Message.SerializeToString,
            response_deserializer=specification__pb2.UpdateHome.FromString,
            _registered_method=True,
        )
        self.GetUndeliveredMessages = channel.unary_stream(
            "/Server/GetUndeliveredMessages",
            request_serializer=specification__pb2.GetMessages.SerializeToString,
            response_deserializer=specification__pb2.MessageList.FromString,
            _registered_method=True,
        )
        self.GetDeliveredMessages = channel.unary_stream(
            "/Server/GetDeliveredMessages",
            request_serializer=specification__pb2.GetMessages.SerializeToString,
            response_deserializer=specification__pb2.MessageList.FromString,
            _registered_method=True,
        )
        self.RefreshHome = channel.unary_stream(
            "/Server/RefreshHome",
            request_serializer=specification__pb2.User.SerializeToString,
            response_deserializer=specification__pb2.UpdateHome.FromString,
            _registered_method=True,
        )
        self.DeleteMessages = channel.unary_stream(
            "/Server/DeleteMessages",
            request_serializer=specification__pb2.DeleteMessage.SerializeToString,
            response_deserializer=specification__pb2.UpdateHome.FromString,
            _registered_method=True,
        )


class ServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Logout(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def SearchUsers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def DeleteAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def SendMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetUndeliveredMessages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetDeliveredMessages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def RefreshHome(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def DeleteMessages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_ServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "CreateUser": grpc.unary_stream_rpc_method_handler(
            servicer.CreateUser,
            request_deserializer=specification__pb2.UserSignup.FromString,
            response_serializer=specification__pb2.UpdateHome.SerializeToString,
        ),
        "Login": grpc.unary_stream_rpc_method_handler(
            servicer.Login,
            request_deserializer=specification__pb2.User.FromString,
            response_serializer=specification__pb2.UpdateHome.SerializeToString,
        ),
        "Logout": grpc.unary_stream_rpc_method_handler(
            servicer.Logout,
            request_deserializer=specification__pb2.User.FromString,
            response_serializer=specification__pb2.Empty.SerializeToString,
        ),
        "SearchUsers": grpc.unary_stream_rpc_method_handler(
            servicer.SearchUsers,
            request_deserializer=specification__pb2.SearchPattern.FromString,
            response_serializer=specification__pb2.UserList.SerializeToString,
        ),
        "DeleteAccount": grpc.unary_stream_rpc_method_handler(
            servicer.DeleteAccount,
            request_deserializer=specification__pb2.User.FromString,
            response_serializer=specification__pb2.Empty.SerializeToString,
        ),
        "SendMessage": grpc.unary_stream_rpc_method_handler(
            servicer.SendMessage,
            request_deserializer=specification__pb2.Message.FromString,
            response_serializer=specification__pb2.UpdateHome.SerializeToString,
        ),
        "GetUndeliveredMessages": grpc.unary_stream_rpc_method_handler(
            servicer.GetUndeliveredMessages,
            request_deserializer=specification__pb2.GetMessages.FromString,
            response_serializer=specification__pb2.MessageList.SerializeToString,
        ),
        "GetDeliveredMessages": grpc.unary_stream_rpc_method_handler(
            servicer.GetDeliveredMessages,
            request_deserializer=specification__pb2.GetMessages.FromString,
            response_serializer=specification__pb2.MessageList.SerializeToString,
        ),
        "RefreshHome": grpc.unary_stream_rpc_method_handler(
            servicer.RefreshHome,
            request_deserializer=specification__pb2.User.FromString,
            response_serializer=specification__pb2.UpdateHome.SerializeToString,
        ),
        "DeleteMessages": grpc.unary_stream_rpc_method_handler(
            servicer.DeleteMessages,
            request_deserializer=specification__pb2.DeleteMessage.FromString,
            response_serializer=specification__pb2.UpdateHome.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "Server", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("Server", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class Server(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateUser(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/Server/CreateUser",
            specification__pb2.UserSignup.SerializeToString,
            specification__pb2.UpdateHome.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Login(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/Server/Login",
            specification__pb2.User.SerializeToString,
            specification__pb2.UpdateHome.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Logout(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/Server/Logout",
            specification__pb2.User.SerializeToString,
            specification__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def SearchUsers(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/Server/SearchUsers",
            specification__pb2.SearchPattern.SerializeToString,
            specification__pb2.UserList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def DeleteAccount(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/Server/DeleteAccount",
            specification__pb2.User.SerializeToString,
            specification__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def SendMessage(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/Server/SendMessage",
            specification__pb2.Message.SerializeToString,
            specification__pb2.UpdateHome.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetUndeliveredMessages(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/Server/GetUndeliveredMessages",
            specification__pb2.GetMessages.SerializeToString,
            specification__pb2.MessageList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetDeliveredMessages(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/Server/GetDeliveredMessages",
            specification__pb2.GetMessages.SerializeToString,
            specification__pb2.MessageList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def RefreshHome(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/Server/RefreshHome",
            specification__pb2.User.SerializeToString,
            specification__pb2.UpdateHome.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def DeleteMessages(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/Server/DeleteMessages",
            specification__pb2.DeleteMessage.SerializeToString,
            specification__pb2.UpdateHome.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
