# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: specification.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'specification.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13specification.proto\"0\n\nUserSignup\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\" \n\rSearchPattern\x12\x0f\n\x07pattern\x18\x01 \x01(\t\"\x19\n\x08UserList\x12\r\n\x05users\x18\x01 \x03(\t\"<\n\x07Message\x12\x0e\n\x06sender\x18\x01 \x01(\t\x12\x10\n\x08receiver\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\"\x18\n\x04User\x12\x10\n\x08username\x18\x01 \x01(\t\"5\n\x0bGetMessages\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x14\n\x0cnum_messages\x18\x02 \x01(\x05\"?\n\x10RetrievedMessage\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06sender\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\"2\n\x0bMessageList\x12#\n\x08messages\x18\x01 \x03(\x0b\x32\x11.RetrievedMessage\".\n\rDeleteMessage\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x0b\n\x03ids\x18\x02 \x01(\t\"8\n\nUpdateHome\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x18\n\x10undeliv_messages\x18\x02 \x01(\x05\"\x07\n\x05\x45mpty2\xba\x03\n\x06Server\x12*\n\nCreateUser\x12\x0b.UserSignup\x1a\x0b.UpdateHome\"\x00\x30\x01\x12\x1f\n\x05Login\x12\x05.User\x1a\x0b.UpdateHome\"\x00\x30\x01\x12\x1b\n\x06Logout\x12\x05.User\x1a\x06.Empty\"\x00\x30\x01\x12,\n\x0bSearchUsers\x12\x0e.SearchPattern\x1a\t.UserList\"\x00\x30\x01\x12\"\n\rDeleteAccount\x12\x05.User\x1a\x06.Empty\"\x00\x30\x01\x12(\n\x0bSendMessage\x12\x08.Message\x1a\x0b.UpdateHome\"\x00\x30\x01\x12\x38\n\x16GetUndeliveredMessages\x12\x0c.GetMessages\x1a\x0c.MessageList\"\x00\x30\x01\x12\x36\n\x14GetDeliveredMessages\x12\x0c.GetMessages\x1a\x0c.MessageList\"\x00\x30\x01\x12%\n\x0bRefreshHome\x12\x05.User\x1a\x0b.UpdateHome\"\x00\x30\x01\x12\x31\n\x0e\x44\x65leteMessages\x12\x0e.DeleteMessage\x1a\x0b.UpdateHome\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'specification_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERSIGNUP']._serialized_start=23
  _globals['_USERSIGNUP']._serialized_end=71
  _globals['_SEARCHPATTERN']._serialized_start=73
  _globals['_SEARCHPATTERN']._serialized_end=105
  _globals['_USERLIST']._serialized_start=107
  _globals['_USERLIST']._serialized_end=132
  _globals['_MESSAGE']._serialized_start=134
  _globals['_MESSAGE']._serialized_end=194
  _globals['_USER']._serialized_start=196
  _globals['_USER']._serialized_end=220
  _globals['_GETMESSAGES']._serialized_start=222
  _globals['_GETMESSAGES']._serialized_end=275
  _globals['_RETRIEVEDMESSAGE']._serialized_start=277
  _globals['_RETRIEVEDMESSAGE']._serialized_end=340
  _globals['_MESSAGELIST']._serialized_start=342
  _globals['_MESSAGELIST']._serialized_end=392
  _globals['_DELETEMESSAGE']._serialized_start=394
  _globals['_DELETEMESSAGE']._serialized_end=440
  _globals['_UPDATEHOME']._serialized_start=442
  _globals['_UPDATEHOME']._serialized_end=498
  _globals['_EMPTY']._serialized_start=500
  _globals['_EMPTY']._serialized_end=507
  _globals['_SERVER']._serialized_start=510
  _globals['_SERVER']._serialized_end=952
# @@protoc_insertion_point(module_scope)
